name: work-1
on:
  push:
    branches:
      - main
jobs:
  hello1:
    runs-on: ubuntu-latest
    outputs:
      username: $username
    steps:
      - name: sayHi
        run: echo "Hi"
      - name: Wait for 3 seconds
        run: sleep 3
      - name: Set username
        id: set_var
        run: echo "::set-output username=${{ github.actor }}" >> $GITHUB_ENV
  hello2:
    needs: [hello1]
    runs-on: ubuntu-latest
    steps:
      - name: sayHi
        run: echo "Hi"
      - name: sayMyName
        run: echo "Username from hello1 is ${{ needs.hello1.outputs.username }}"
